### ISSUE TITLE
check-data is failing

### ISSUE THREAD

**Issue by dematerializer** [dematerializer/unicode-emoji-data#4]
replace is not a function --> datum.sequence is undefined
This is a regression error introduced by 62248fa146c4aebbf9d92fd056b33d43556e1f66 when I changed expandEmojiData to "not derive new data" (like the sequence property)
